services:
  astro:
    container_name: ${NAME}-astro
    restart: unless-stopped
    build:
      target: astro
    ports:
      - 3000:80
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.${NAME}-astro.rule=Host(`${ASTRO_HOST}`)
    #   - traefik.http.routers.${NAME}-astro.entrypoints=https
    #   - traefik.http.routers.${NAME}-astro.tls.certresolver=httpresolver
    #   - traefik.docker.network=traefik_network
    # networks:
    #   - traefik_network
    depends_on:
      - payload

  payload:
    container_name: ${NAME}-payload
    restart: unless-stopped
    build:
      target: payload
    environment:
      NAME: ${NAME}
      PAYLOAD_URL: ${PAYLOAD_URL}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      MONGODB_URI: ${MONGODB_URI}
      TOKEN: ${TOKEN}
      REPOSITORY: ${REPOSITORY}
    volumes:
      - ./data/media:/prod/dist/media
    ports:
      - 3001:3001
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.${NAME}-payload.rule=Host(`${PAYLOAD_HOST}`)
    #   - traefik.http.routers.${NAME}-payload.entrypoints=https
    #   - traefik.http.routers.${NAME}-payload.tls.certresolver=httpresolver
    #   - traefik.docker.network=traefik_network
    # networks:
    #   - traefik_network
    #   - back
    depends_on:
      - mongo

  mongo:
    container_name: ${NAME}-mongo
    image: mongo:6.0.5
    restart: unless-stopped
    volumes:
      - ./data/mongo:/data/db
    command:
      - --storageEngine=wiredTiger
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PW}
#     networks:
#       - back

# networks:
#   back:
#   traefik_network:
#     external: true
