services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: payload
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    
    